<template>
  <div class="template"><!-- Title class must be the same as it is in router/index.js -->
    <div class="page"> <!-- similar to body but used for separate styling -->
      <div class="content"> <!-- where everything goes content -->


      </div> <!-- end of content -->
    </div> <!-- end of page -->

<div class="footer">
  <a href="https://github.com/Ki11erRabbit/Creative-Project-3"> GitHub
    <p>Made by Alec Davis and Louisa Dayton</p></a>
</div>

  </div>
</template>

<style>


</style>
